-- AlterTable
ALTER TABLE `CaseReg` ADD COLUMN `acquired_date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `acts` JSON NULL,
    ADD COLUMN `case_date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `court_order` VARCHAR(191) NOT NULL DEFAULT 'Pending',
    ADD COLUMN `crime_number` VARCHAR(191) NOT NULL DEFAULT 'Unknown',
    ADD COLUMN `guilty_details` VARCHAR(191) NOT NULL DEFAULT 'Not specified';
